# R8 / minify keep-rules (Phase 5.3 — "begin"; Phase 6 tightens + adds resource shrink).
#
# Strategy: R8 still removes the big unused weight (material-icons-extended,
# unused androidx/Compose), but the LLM provider SDKs and their reflective JSON
# stacks are kept whole so runtime reflection (Jackson/Gson/protobuf, builders,
# model types, sealed/enum hierarchies) cannot be stripped. Narrowing these to
# minimal targeted rules is deferred to Phase 6's final shrink/verify.

# --- Provider SDKs (agent/llm) ---
-keep class com.anthropic.** { *; }
-keep class com.google.genai.** { *; }
-dontwarn com.anthropic.**
-dontwarn com.google.genai.**

# LiteRT-LM on-device runtime (Phase 5.5b): JNI-bound native runtime — keep the
# Kotlin/Java surface whole so reflection/JNI entry points aren't stripped.
-keep class com.google.ai.edge.litertlm.** { *; }
-keep class com.google.ai.edge.litert.** { *; }
-dontwarn com.google.ai.edge.**

# --- Reflective JSON / transport stacks the SDKs pull in ---
-keep class com.fasterxml.jackson.** { *; }
-keep class com.google.protobuf.** { *; }
-keep class com.google.api.client.** { *; }
-keep class com.google.gson.** { *; }
-dontwarn com.fasterxml.jackson.**
-dontwarn com.google.protobuf.**
-dontwarn com.google.api.client.**
-dontwarn com.google.gson.**

# OkHttp / Okio (Anthropic SDK transport) ship their own consumer rules, but be
# explicit about the platform-specific warnings R8 surfaces.
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**

# --- Compile-only annotations referenced by the above (not on the runtime path) ---
-dontwarn com.google.errorprone.**
-dontwarn org.checkerframework.**
-dontwarn javax.annotation.**
-dontwarn javax.lang.model.**
-dontwarn java.lang.management.**

# Optional JVM/desktop classes referenced by transitive deps (victools jsonschema,
# apache-http auth/ssl) that don't exist on Android — never on our runtime path.
# Generated by R8's missing_rules.txt.
-dontwarn java.lang.reflect.AnnotatedParameterizedType
-dontwarn java.lang.reflect.AnnotatedType
-dontwarn javax.naming.**
-dontwarn org.ietf.jgss.**

# Preserve generics, annotations, and inner-class metadata the JSON libraries
# read reflectively (Gson TypeToken, Jackson @JsonProperty, AutoValue, etc.).
-keepattributes Signature,*Annotation*,EnclosingMethod,InnerClasses,RuntimeVisibleAnnotations,RuntimeVisibleParameterAnnotations
